#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Initialize and synchronize the LineageOS source tree for WeaR OS.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ -f "$ROOT_DIR/../build/envsetup.sh" ]]; then
    ANDROID_DIR="${ANDROID_DIR:-$ROOT_DIR/..}"
elif [[ -f "$ROOT_DIR/../../build/envsetup.sh" ]]; then
    ANDROID_DIR="${ANDROID_DIR:-$ROOT_DIR/../..}"
else
    ANDROID_DIR="${ANDROID_DIR:-$ROOT_DIR/..}"
fi

STACK="${STACK:-23.1-snapboss}"

case "$STACK" in
    23.2-experimental)
        MANIFEST_TEMPLATE="$ROOT_DIR/manifests/duchamp-lineage-23.2.xml"
        DEFAULT_LINEAGE_REF="eabe68377217a88c81fa933db0136ea4146ff369"
        ;;
    23.1-snapboss)
        MANIFEST_TEMPLATE="$ROOT_DIR/manifests/duchamp-lineage-23.1.xml"
        DEFAULT_LINEAGE_REF="7d408383a8f199ba9a72e8a3b4314c6d848b459c"
        ;;
    *)
        echo "ERROR: unsupported STACK='$STACK'." >&2
        echo "Supported values: 23.1-snapboss, 23.2-experimental" >&2
        exit 1
        ;;
esac

LINEAGE_REF="${LINEAGE_REF:-$DEFAULT_LINEAGE_REF}"
JOBS="${JOBS:-4}"
WEAR_REF="${WEAR_REF:-main}"

command -v repo >/dev/null 2>&1 || {
    echo "ERROR: 'repo' is not installed or not in PATH." >&2
    exit 1
}

cd "$ANDROID_DIR"

repo init -u https://github.com/LineageOS/android.git \
    -b "$LINEAGE_REF" \
    --git-lfs

mkdir -p .repo/local_manifests
MANIFEST_OUT=".repo/local_manifests/wear-duchamp.xml"

python3 - "$MANIFEST_TEMPLATE" "$MANIFEST_OUT" "$WEAR_REF" <<'PY'
from pathlib import Path
import sys

src = Path(sys.argv[1])
dst = Path(sys.argv[2])
wear_ref = sys.argv[3]

data = src.read_text(encoding="utf-8")
needle = '''name="RidTheWann/WeaR-OS"
        remote="github"
        revision="main"'''
replacement = f'''name="RidTheWann/WeaR-OS"
        remote="github"
        revision="{wear_ref}"'''

if needle not in data:
    raise SystemExit("ERROR: WeaR project entry was not found in the selected manifest template.")

dst.write_text(data.replace(needle, replacement, 1), encoding="utf-8")
PY

cat > .repo/local_manifests/wear-source.env <<EOF
# Generated by scripts/sync.sh. Do not commit this file.
STACK=$STACK
LINEAGE_REF=$LINEAGE_REF
WEAR_REF=$WEAR_REF
MANIFEST_TEMPLATE=$MANIFEST_TEMPLATE
EOF

SYNC_ARGS=(
    "-c"
    "--no-clone-bundle"
    "--no-tags"
    "-j$JOBS"
)

if [[ "${FORCE_SYNC:-0}" == "1" ]]; then
    SYNC_ARGS+=("--force-sync")
fi

echo "==> WeaR stack : $STACK"
echo "==> Lineage ref: $LINEAGE_REF"
echo "==> WeaR ref   : $WEAR_REF"
echo "==> Sync jobs  : $JOBS"

repo sync "${SYNC_ARGS[@]}"

echo
echo "Source synchronization complete."
echo "Run scripts/verify-source.sh before the first build."
